<?php
    /*
        Cette fois ci nos routes sont un peu plus complexe.
        Elles vont être liées à la fois à un controller
        Mais aussi à une fonction.
    */
    const ROUTES = [
        "05-mvc"=>[
            "controller"=>"userController.php",
            "fonction"=>"readUsers"
        ],
        "05-mvc/inscription"=>[
            "controller"=>"userController.php",
            "fonction"=>"createUser"
        ],
        "05-mvc/update"=>[
            "controller"=>"userController.php",
            "fonction"=>"updateUser"
        ],
        "05-mvc/delete"=>[
            "controller"=>"userController.php",
            "fonction"=>"deleteUser"
        ],
        "05-mvc/connexion"=>[
            "controller"=>"userController.php",
            "fonction"=>"connectUser"
        ],
        "05-mvc/deconnexion"=>[
            "controller"=>"userController.php",
            "fonction"=>"deconnectUser"
        ],
        "05-mvc/list"=>[
            "controller"=>"messageController.php",
            "fonction"=>"seeMessage"
        ],
        "05-mvc/list/updateMessage"=>[
            "controller"=>"messageController.php",
            "fonction"=>"updateMessage"
        ],
        "05-mvc/list/deleteMessage"=>[
            "controller"=>"messageController.php",
            "fonction"=>"deleteMessage"
        ],
        "05-mvc/createMessage"=>[
            "controller"=>"messageController.php",
            "fonction"=>"createMessage"
        ]
    ];
?>